<link rel="stylesheet" type="text/css" media="screen" href="css/allpage.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/allpage.light.css">

<link rel="stylesheet" type="text/css" media="screen" href="css/navbar.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/navbar.light.css">

<link rel="stylesheet" type="text/css" media="screen" href="css/footer.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/footer.light.css">

<link rel="stylesheet" type="text/css" media="screen" href="css/particule.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/particule.light.css">

<link rel="stylesheet" type="text/css" media="screen" href="css/home.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/home.light.css">

<link rel="stylesheet" type="text/css" media="screen" href="css/service.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/service.light.css">

<link rel="stylesheet" type="text/css" media="screen" href="css/project.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/project.light.css">

<link rel="stylesheet" type="text/css" media="screen" href="css/collaboration.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/collaboration.light.css">

<link rel="stylesheet" type="text/css" media="screen" href="css/story.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/story.light.css">

<link rel="stylesheet" type="text/css" media="screen" href="css/contact.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/contact.light.css">

<link rel="stylesheet" type="text/css" media="screen" href="css/popup.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/popup.light.css">

<link rel="stylesheet" type="text/css" media="screen" href="css/connect.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/tyrobtn.css">

<script src="javascript/redirect.js"></script>
<script src="javascript/navbar.js"></script>
<script src="javascript/cheatcode.js"></script>
<script src="javascript/project.js"></script>