<link rel="stylesheet" type="text/css" media="screen" href="css/allpage.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/navbar.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/footer.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/particule.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/home.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/service.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/project.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/collaboration.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/story.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/account.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/tyrobtn.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/contact.css">
<script src="javascript/redirect.js"></script>
<script src="javascript/navbar.js"></script>
<script src="javascript/cheatcode.js"></script>