<link rel="stylesheet" type="text/css" media="screen" href="css/allpage.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/navbar.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/index.css">
<link rel="stylesheet" type="text/css" media="screen" href="css/project.css">
<script src="javascript/redirect.js"></script>
<script src="javascript/navbar.js"></script>