<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6><?= $lang['footer']["title"][0] ?></h6>
                <p class="text-justify"><?= $lang['footer']["about-text"] ?></p>
            </div>

            <div class="footlink col-xs-6 col-md-3">
                <h6><?= $lang['footer']["title"][1] ?></h6>
                <ul class="footer-links">
                    <?php  $nbBack = count($env_page);

                    for ($i = 0; $i <= $nbBack-1; $i++) {
                        $j = 0;
                        $j = $i+1;

                        if ($env_isAccount == false && $j <= 5){
                            echo '<li><a href="javascript:redirect('. $j .');">'. $lang['page'][$i] .'</a></li>';
                        } else if ($env_isAccount == true) {
                            echo '<li><a href="javascript:redirect('. $j .');">'. $lang['page'][$i] .'</a></li>';
                        }

                    }?>
                </ul>
            </div>

            <div class="footlink col-xs-6 col-md-3">
                <h6><?= $lang['footer']["title"][2] ?></h6>
                <ul class="footer-links">
                    <li><a href="more.php"><?= $lang["footer"]["other-page"][0] ?></a></li>
                    <li><a href="contact.php"><?= $lang["footer"]["other-page"][1] ?></a></li>
                    <li><a href="https://tyrolium.fr/Status/"><?= $lang["footer"]["other-page"][2] ?></a></li>
                    <li><a href="https://tyrolium.fr/Panel/"><?= $lang['footer']["other-page"][3] ?></a></li>
                    <li><a href="https://github.com/orgs/Tyrolium/repositories"><?= $lang['footer']["other-page"][4] ?></a></li>
                    <li><a href="https://birthday.tyrolium.fr/"><?= $lang['footer']["other-page"][5] ?></a></li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text">Copyright &copy; 2017-2022 All Rights Reserved by
                    <a href="/">Tyrolium</a>.
                </p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <ul class="social-icons">
                    <li><a class="facebook" href="https://www.facebook.com/tyrolium/"><i class="fab fa-facebook footer"></i></a></li>
                    <li><a class="instagram" href="https://www.instagram.com/tyroliumentertainment/"><i class="fab fa-instagram footer"></i></a></li>
                    <li><a class="twitter" href="https://twitter.com/TyroliumE"><i class="fab fa-twitter footer"></i></a></li>
                    <li><a class="youtube" href="https://www.youtube.com/channel/UCY7TQJxzGSawF0YnixBAAXA"><i class="fab fa-youtube footer"></i></a></li>
                    <li><a class="discord" href="https://discord.gg/km8h5jHezt"><i class="fab fa-discord footer"></i></a></li>
                    <li><a class="linkedin" href="https://www.linkedin.com/company/tyrolium"><i class="fab fa-linkedin footer"></i></a></li>
                    <li><a class="tiktok" href="https://www.tiktok.com/@tyrolium"><i class="fab fa-tiktok footer"></i></a></li>
                    <li><a class="twitch" href="https://twitch.tv/tyrolium"><i class="fab fa-twitch footer"></i></a></li>
                    <li><a class="github" href="https://github.com/tyrolium"><i class="fab fa-github footer"></i></a></li>
                    <li><a class="gettr" href="https://gettr.com/user/tyrolium"><i class="fas fa-fire footer"></i></a></li>
                    <li><a class="telegram" href="https://t.me/tyrolium"><i class="fab fa-telegram-plane footer"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>