<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6>à propos</h6>
                <p class="text-justify">Tyrolium est une entreprise multifonction qui travaille sur plusieurs projets, notamment du développement de jeux vidéos ou d'applications web, de la musique, ou de l'audiovisuel.

                    Elle propose principalement des prestations de services de création de site Web et d'applications pour les particuliers et les professionnels.

                    Les profits générés par ces prestations seront directement investies dans les projets de l'entreprise.</p>
            </div>

            <div class="footlink col-xs-6 col-md-3">
                <h6>CATÉGORIES</h6>
                <ul class="footer-links">
                    <li><a href="javascript:redirect(1);">Home</a></li>
                    <li><a href="javascript:redirect(2);">Service</a></li>
                    <li><a href="javascript:redirect(3);">Projet</a></li>
                    <li><a href="javascript:redirect(4);">Collaboration</a></li>
                    <li><a href="javascript:redirect(5);">Histoire</a></li>
                </ul>
            </div>

            <div class="footlink col-xs-6 col-md-3">
                <h6>LIENS RAPIDES</h6>
                <ul class="footer-links">
                    <li><a href="#">About Us</a></li>
                    <li><a href="https://tyrolium.fr/Panel/">Panel Admin</a></li>
                    <li><a href="https://tyrolium.fr/Status/">Status Server</a></li>
                    <li><a href="#">Github</a></li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text">Copyright &copy; 2017-2022 All Rights Reserved by
                    <a href="#">Tyrolium</a>.
                </p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <ul class="social-icons">
                    <li><a class="facebook" href="https://www.facebook.com/tyrolium/"><i class="fab fa-facebook footer"></i></a></li>
                    <li><a class="instagram" href="https://www.instagram.com/tyroliumentertainment/"><i class="fab fa-instagram footer"></i></a></li>
                    <li><a class="twitter" href="https://twitter.com/TyroliumE"><i class="fab fa-twitter footer"></i></a></li>
                    <li><a class="youtube" href="https://www.youtube.com/channel/UCY7TQJxzGSawF0YnixBAAXA"><i class="fab fa-youtube footer"></i></a></li>
                    <li><a class="discord" href="https://discord.gg/km8h5jHezt"><i class="fab fa-discord footer"></i></a></li>
                    <li><a class="linkedin" href="https://www.linkedin.com/company/tyrolium"><i class="fab fa-linkedin footer"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>