<li class="nav-item active">
    <a class="nav-link active" href="javascript:void(0);"><i class="fas fa-home"></i>Home</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="javascript:redirect(2);"><i class="fas fa-tags"></i>Service</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="javascript:redirect(3);"><i class="fas fa-dice-d6"></i>Projet</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="javascript:redirect(4);"><i class="far fa-handshake"></i>Colaboration</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="javascript:redirect(5);"><i class="fas fa-book"></i>Histoire</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="javascript:redirect(6)"><i class="far fa-user"></i>Compte</a>
</li>