<nav class="navbar navbar-expand-custom navbar-mainbg navbar-dark fixed-top">
    <img style="margin-left: 20px" src="http://tyrolium.fr/Contenu/Image/<?php if ($env_isEvent_5Year) { echo "Tyrolium5Year Site.png"; } else { echo "Tyrolium Site.png"; } ?>" alt="TyroliumLogo" width="40px" class="d-inline-block align-text-top nav-anim">
    <a class="navbar-brand navbar-logo" href="javascript:redirect(1)">Tyrolium <?php if($env_isEvent_5Year){?><span class="badge badge-warning">5 ans !</span><?php } ?></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
            <?php $nbBack = count($env_page);

for ($i = 0; $i <= $nbBack-1; $i++) {
    $j = 0;
    $j = $i+1;

    if ($env_isAccount == false && $j <= 5){
            if ($j == $page){
                echo '<li class="nav-item active">
                          <a class="nav-link active" href="javascript:void(0);"><i class="'. $env_page_logo[$i] .'"></i>'. $lang['page'][$i] .'</a>
                      </li>';
            } else {
                echo '<li class="nav-item">
                          <a class="nav-link" href="javascript:redirect('. $j .');"><i class="'. $env_page_logo[$i] .'"></i>'. $lang['page'][$i] .'</a>
                      </li>';
            }

    } else if ($env_isAccount == true) {

            if ($j == $page){
                echo '<li class="nav-item active">
                              <a class="nav-link active" href="javascript:void(0);"><i class="'. $env_page_logo[$i] .'"></i>'. $lang['page'][$i] .'</a>
                          </li>';
            } else {
                echo '<li class="nav-item">
                              <a class="nav-link" href="javascript:redirect('. $j .');"><i class="'. $env_page_logo[$i] .'"></i>'. $lang['page'][$i] .'</a>
                          </li>';
            }
    }

}?>
            
            
            <!--LANG TEMPORAIRE-->
            <li class="nav-item lang">
                <?php if ($_SESSION['lang'] == "fr_FR"){ ?>
    
                <a href="?lang=en_US"><img src="https://flagicons.lipis.dev/flags/4x3/fr.svg" alt="fr"></a>
    
                <?php } else { ?> 
                
                <a href="?lang=fr_FR"><img src="https://flagicons.lipis.dev/flags/4x3/gb.svg" alt="gb"></a>
                
                <?php } ?>
            </li>
            
            <style>
            
                
                
                #navbarSupportedContent ul li.lang a{
                    padding-top: 20px;
                    padding-right: 11px;
                    padding-bottom: 20px;
                    padding-left: 0px;
                }
            
                li.lang img{
                    width: 25px;
                    
                }
            
            </style>
            <!--LANG TEMPORAIRE-->   
                
                
        </ul>
        <div style="width: 40px;"></div>
        <div class="btn-darkmode"><?php if (empty($_COOKIE["color"])){ echo "<i class='fas fa-moon'></i>"; }else{ if ($_COOKIE["color"] == "light"){ ?><i class="fas fa-sun"></i><?php }else{ ?><i class="fas fa-moon"></i><?php }  } ?></div>
        <script src="javascript/darkmode.js"></script>
    </div>
</nav>

<?php if ($env_isEvent_5Year) { ?>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
<script src='https://unpkg.com/izitoast/dist/js/iziToast.min.js'></script>

<script>
        iziToast.settings({
            timeout: 3000,
            resetOnHover: true,
            transitionIn: 'flipInX',
            transitionOut: 'flipOutX',
            position: 'topRight',
            onOpen: function () {
                console.log('callback abriu!');
            },
            onClose: function () {
                console.log("callback fechou!");
            }
        });

        if(Text != 1){
            iziToast.info({
                title: '5 ans !',
                theme: 'light',

                iconUrl: 'https://tyrolium.fr/Contenu/Image/Tyrolium%20Site.png',

                backgroundColor: '#ffc107',

                timeout: 20000,

                position: 'bottomCenter',
                message: ' Tyrolium souffle sa 5ieme bougie 🎉 <a target="_blank" href="https://www.youtube.com/watch?v=fRjkVPeCDDI" style="text-decoration: underline">Regarder la vidéo de l\'annivairesaire</a>'
            });
        }
</script> <?php } ?>