<nav class="navbar navbar-expand-custom navbar-mainbg navbar-dark fixed-top">
        <img style="z-index: 10000; margin-left: 20px" src="http://tyrolium.fr/Contenu/Image/<?php if ($env_isEvent_5Year) { echo "Tyrolium5Year Site.png"; } else { echo "Tyrolium Site.png"; } ?>" alt="TyroliumLogo" width="40px" class="d-inline-block align-text-top nav-anim">
        <a style="z-index: 10000;" class="navbar-brand navbar-logo" href="javascript:redirect(1)">Tyrolium <?php if($env_isEvent_5Year){?><span class="badge badge-warning">7 ans !</span><?php } ?> <?php if($env_isEvent_Noel2022){?> <span class="badge badge-danger">Joyeux Noël !</span><?php } ?>  <?php if($env_isEvent_year2023){?> <span class="badge badge-success">Bonne Année 2023 !</span><?php } ?></a>

    <div>
        <div class="darkMobile btn-darkmode btn-darkmode1"><?php if (empty($_COOKIE["color"])){ echo "<i class='fas fa-moon'></i>"; }else{ if ($_COOKIE["color"] == "light"){ ?><i class="fas fa-sun"></i><?php }else{ ?><i class="fas fa-moon"></i><?php }  } ?></div>
        
        <button class=" navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
            <?php $nbBack = count($env_page);

for ($i = 0; $i <= $nbBack-1; $i++) {
    $j = 0;
    $j = $i+1;

    if ($env_isAccount == false && $j <= 5){
            if ($j == $page){
                echo '<li class="nav-item active">
                          <a class="nav-link active" href="javascript:void(0);"><i class="'. $env_page_logo[$i] .'"></i>'. $lang['page'][$i] .'</a>
                      </li>';
            } else {
                echo '<li class="nav-item">
                          <a class="nav-link" href="javascript:redirect('. $j .');"><i class="'. $env_page_logo[$i] .'"></i>'. $lang['page'][$i] .'</a>
                      </li>';
            }

    } else if ($env_isAccount == true) {

        if ($j == 3){

            //TEST PARTI PRESTATION
            if ($j == $page){
                echo '<li class="nav-item active"  onmouseover="showDropdown()" onmouseout="hideDropdown()">   ';
            } else {
                echo '<li class="nav-item"  onmouseover="showDropdown()" onmouseout="hideDropdown()">   ';
            }
            echo '<a class="nav-link" href="javascript:void('. $j .');"><i class="'. $env_page_logo[$i] .'"></i>'. $lang['page'][$i] .' <i id="dropdown-Icone" class="fas fa-chevron-down"></i> </a>
                     <div class="dropdown-content">
                        
                        <hr>
                        <h2 onclick="window.location.href = \'website.php\';"><i class="fas fa-globe"></i> <span>'. $lang['service-page'][0]['name'] .'</span> '. $lang['service-page'][0]['sub'] .'</h2>
                        <h2 onclick="window.location.href = \'server.php\';"><i class="fas fa-server"></i> <span>'. $lang['service-page'][1]['name'] .'</span> '. $lang['service-page'][1]['sub'] .'</h2>
                        <h2 onclick="window.location.href = \'minecraft.php\';"><img class="mc-icone" src="https://www.pngall.com/wp-content/uploads/13/Minecraft-Logo-PNG-Image.png" alt="Minecraft Icone"> <span>'. $lang['service-page'][2]['name'] .'</span> '. $lang['service-page'][2]['sub'] .'</h2>
                        <h2 onclick="window.location.href = \'https://nexiumiacrm.fr\';"><i class="fas fa-tasks"></i> <span>'. $lang['service-page'][3]['name'] .'</span> '. $lang['service-page'][3]['sub'] .'</h2>
                        <!-- <h2 onclick="window.location.href = \'video.php\';" style="margin-top: -2px;"><i class="fas fa-film"></i> <span>Montage & Vidéo</span> <small>Par notre partenaire 49 Volts <img style="margin-top: -5px;" src="assets/part/49volts Site.png" alt="49volts logo"></small> </h2> -->
                    </div>
                  </li>';
//<h2 onclick="window.location.href = \'video\';"><i class="fas fa-film"></i> <span>Montage & Vidéo</span> <small>Par notre partenaire 49 Volts <img style="margin-top: -5px;" src="assets/part/49volts Site.png" alt="49volts logo"></small> </h2>



            ?>


                <style>

                    @media (max-width: 991px) {
                        .dropdown-content {
                            width: 100%;
                        }
                    }


                    #dropdown-Icone{
                        font-size: 12px;
                        margin-right: -8px !important;
                        margin-left: 2px;
                    }

                    /* Style de base pour le menu déroulant (caché initialement) */
                    .dropdown-content {
                        border-bottom-left-radius: 10px;
                        border-bottom-right-radius: 10px;
                        display: none;
                        position: absolute;
                        background-color: #26272be0!important;
                        backdrop-filter: blur(20px)!important;
                        min-width: 160px;
                        /*box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);*/
                        z-index: 1;
                        padding: 20px
                    }

                    body.light .dropdown-content {
                        background-color: rgba(255, 255, 255, 0.94) !important;
                        backdrop-filter: blur(20px)!important;
                    }

                    .dropdown-content hr{
                        margin-top: -10px;
                        background: white;
                    }
                    .dropdown-content .mc-icone{
                        width: 26px;
                        filter: invert(1);
                        margin-left: -3px;
                        margin-top: -5px;
                        margin-right: 7px;

                        opacity: unset!important;
                        animation: unset!important;
                        transform: unset!important;
                    }

                    body.light .dropdown-content .mc-icone{
                        filter: invert(0);
                    }

                    .dropdown-content h2{
                        margin-bottom: 10px;
                    }
                    .dropdown-content span:hover{
                        text-decoration: underline;
                    }
                    .dropdown-content small{
                        margin-left: 10px;
                        font-size: 10px;
                        text-align: end;
                    }
                    .dropdown-content small img{
                        width: 20px;
                        opacity: unset!important;
                        animation: unset!important;
                        transform: unset!important;
                    }

                    /* Style pour les éléments du menu déroulant */
                    .dropdown-content a {
                        color: black;
                        padding: 12px 16px;
                        text-decoration: none;
                        display: block;
                    }

                    /* Style pour le survol des éléments du menu déroulant */
                    .dropdown-content a:hover {
                        background-color: #f1f1f1;
                    }

                </style>

            <script>
                function showDropdown() {
                    document.querySelector('.dropdown-content').style.display = 'block';
                }

                function hideDropdown() {
                    document.querySelector('.dropdown-content').style.display = 'none';
                }
            </script>






            <?php


        } else {
            if ($j == $page && $j != 5){

                if ($page != 7) {
                    echo '<li class="nav-item active">
                                  <a class="nav-link active" href="javascript:void(0);"><i class="' . $env_page_logo[$i] . '"></i>' . $lang['page'][$i] . '</a>
                              </li>';
                } else {
                    echo '<li class="nav-item active">
                                  <a class="nav-link active" href="javascript:void(0);">' . $lang['page'][$i] . '</a>
                              </li>';
                }

            } else if ($j != 5 && $j != 7) {
                echo '<li class="nav-item">
                              <a class="nav-link" href="javascript:redirect('. $j .');"><i class="'. $env_page_logo[$i] .'"></i>'. $lang['page'][$i] .'</a>
                          </li>';
            } else if ($j == 7) {
                echo '<li class="nav-item contactus">
                              <a class="nav-link contactus" href="javascript:redirect('. $j .');">'. $lang['page'][$i] .'</a>
                          </li>';
                ?>

                <style>

                    /*@media(min-width: 992px){*/

                        #navbarSupportedContent>ul>li.contactus>a {
                            padding-bottom: 13px;
                            padding-top: 15px;
                            margin-top: 6px;
                            transition-duration: 0.6s;
                            transition-timing-function: cubic-bezier(0.68, -0.55, 0.265, 1.55);
                            background-color: #001cfa6b;
                            border-radius: 15px;
                            box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px, rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px;
                        }
                        
                    /*}*/

                </style>

                <?php
            }
        }
    }

}?>
            
            <?php if ($env_isMultilang == true){ ?>
            <!--LANG TEMPORAIRE-->
            <li class="nav-item lang">
                <?php
                if ($_SESSION['lang'] == "fr_FR"){ ?>
    
                <a href="?lang=en_US"><img src="https://flagicons.lipis.dev/flags/4x3/fr.svg" alt="fr"></a>
    
                <?php } else { ?> 
                
                <a href="?lang=fr_FR"><img src="https://flagicons.lipis.dev/flags/4x3/gb.svg" alt="gb"></a>
                
                <?php } ?>
            </li>
            <style>
            
                
                
                #navbarSupportedContent ul li.lang a{
                    padding-top: 20px;
                    padding-right: 11px;
                    padding-bottom: 20px;
                    padding-left: 0px;
                }
            
                li.lang img{
                    width: 25px;
                    
                }
            
            </style>
            <!--LANG TEMPORAIRE-->   
            <?php } ?>    
                
        </ul>
        <div style="width: 40px;"></div>
        <div class="darkDesktop btn-darkmode btn-darkmode2"><?php if (empty($_COOKIE["color"])){ echo "<i class='fas fa-moon'></i>"; }else{ if ($_COOKIE["color"] == "light"){ ?><i class="fas fa-sun"></i><?php }else{ ?><i class="fas fa-moon"></i><?php }  } ?></div>
        <script src="javascript/darkmode.js"></script>
    </div>
</nav>

<?php if ($env_isEvent_5Year) { ?>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
<script src='izitoast-1.4.0/iziToast.min.js'></script>

<script>
        iziToast.settings({
            timeout: 3000,
            resetOnHover: true,
            transitionIn: 'flipInX',
            transitionOut: 'flipOutX',
            position: 'topRight',
            onOpen: function () {
                console.log('callback abriu!');
            },
            onClose: function () {
                console.log("callback fechou!");
            }
        });

        if(Text != 1){
            iziToast.info({
                title: '7 ans !',
                theme: 'light',

                iconUrl: 'https://tyrolium.fr/Contenu/Image/Tyrolium%20Site.png',

                backgroundColor: '#ffc107',

                timeout: 20000,

                position: 'bottomCenter',
                message: ' Tyrolium souffle sa 7ieme bougie 🎉'
            });
        }
</script> <?php } ?>

<?php if ($env_isEvent_TyroServ) { ?>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
<script src='izitoast-1.4.0/iziToast.min.js'></script>

<script>
        iziToast.settings({
            timeout: 3000,
            resetOnHover: true,
            transitionIn: 'flipInX',
            transitionOut: 'flipOutX',
            position: 'topRight',
            onOpen: function () {
                console.log('callback abriu!');
            },
            onClose: function () {
                console.log("callback fechou!");
            }
        });

        if(Text != 1){
            iziToast.info({
                title: 'TYROSERV !',
                theme: 'light',

                iconUrl: 'https://tyrolium.fr/Contenu/Image/Tyrolium%20ServerMC%20Sword%203D.png',

                backgroundColor: '#41b841',

                timeout: 20000,

                position: 'bottomCenter',
                message: ' TyroServ, notre projet Minecraft, a lancé une nouvelle saison.<br> Pour jouer, rendez-vous sur son site. <a target="_blank" href="https://tyroserv.fr" style="text-decoration: underline">Site de TyroServ</a>'
            });
        }
</script> 
<style>


.iziToast-title{

    margin-top: 8px!important;

}

</style>

<?php } ?>

<div style="height: 64px"></div>
