<?php

    $lang = array(
        
        "page" => array(
        
            "Home",
            "Service",
            "Project",
            "Collaboration",
            "Story",
            "Account"
        
        ),
        
        "footer" => array(
            
            "title" => array(
        
                "About",
                "pages",
                "Other links"
        
            ),
            
            "other-page" => array(
        
                "More Info",
                "Contact",
                "Server API",
                "Admin Panel",
                "Repository",
                "Birthday"

            ),
            
            "about-text" => "Tyrolium is a multi-sector company that works on several projects, mainly on Web development but also in particular on the development of games or video, musical or audiovisual applications. It mainly offers website and application creation services for individuals and professionals. The profits generated by these services will be directly invested in the company's projects."
        
        ),
        
        1 => array(
        
            "head" => "FIND OUT WHO WE ARE", //DISCOVER WHO WE ARE
        
            "about" => array(
            
                "title" => "About Tyrolium",
                "txt" => 'Tyrolium is a multi-sector company that works on several projects, mainly on Web development but also in particular on the development of games or video, musical or audiovisual applications.</h3>
                <br>
                <h3 class="art">It mainly offers website and application creation services for individuals and professionals.</h3>
                <br>
                <h3 class="art">The profits generated by these services will be directly invested in the company\'s projects.'
            
            ),
            
            "service" => array(
            
                "title" => "Our services",
                "btn" => "null",
                "txt" => "Tyrolium offers you services, in particular in the development of websites, applications, server hosting, development of minecraft and bots (discord or other) for individuals and professionals. The funds generated by these services will be invested in the company's projects."
            
            ),
            
            "project" => array(
            
                "title" => "Our projects",
                "btn" => "null",
                "txt" => "Nowadays, many of us dream of creating our own projects. Tyrolium has succeeded in making the dreams of our passionate employees come true. We are proud of what we accomplish every day. We offer you large-scale projects always with the passion of all our teams. Tyrolium wants to offer you well-done projects, something to entertain you or make your life easier."
            
            ),
            
            "collab" => array(
            
                "title" => "Our Collaborations",
                "btn" => "null",
                "txt" => "Tyrolium is a company which is made up of several teams, they are mainly directed in the projects of the company as well as the services offered. These teams are made up of motivated, dynamic people who are invested in the projects and in the company. We recruit any type of profile, the only prerequisites are to be interested and motivated by the projects that attract you"
            
            ),
            
            "account" => array(
            
                "title" => "Useritium Accounts",
                "btn" => "More Info",
                "txt" => "Useritium accounts are offered by Tyrolium, in order to offer you a personal email address. These accounts offer you a cloud, moreover, they also allow you to manage your video games, your servers. They also allow you to know the progress of your claims for benefits. These accounts are also a guarantee of the security of your data, we undertake never to share or divulge any information concerning you."
            
            ),
            
            "story" => array(
            
                "title" => "Our history",
                "btn" => "null",
                "txt" => "Tyrolium has existed since 2017 and has matured projects and the people who have worked and are still working on them. During these 5 years, an evolution has been felt and we will detail this evolution in chronological order and tell you the key points of it. Don't forget however that evolution is not the end, it is only the beginning of the push that will take us to the top, as long as we can do better it will never be over."
            
            ),
            
            "french" => array(
            
                "title" => "Independent and French",
                "txt" => "Tyrolium's goal is to make the most of the potential of its employees to create ever more ambitious projects. The funds generated by our services are injected into the company to finance projects. Tyrolium's objective is to compete with the world and the giants of our field while remaining French. Made in France, by French people."
            
            ),
            
        ),
    
    
    
    
    
    )


?>